#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
var=1
while [ "$var" -le 10 ]; do
	if [ "$var" -eq 4 ]
	then
		echo "Bad luck"
	elif [ "$var" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var++))
done
